### ISSUE TITLE
Can edit with find and replace while in readonly mode

### ISSUE THREAD

**Issue by jepetty** [microsoft/vscode-remote-repositories-github#109]
When a repository is in readonly mode, either with an explicit set for GitHub repos or Azure DevOps by default, you can still make edits by utilizing "Find and Replace".

**Repro Steps:**
1. Search for a term using Ctrl+F or Ctrl+Shft+F in and Azure DevOps repository or while viewing a GitHub repository in a readonly state
2. Select "Replace All" to replace all instances of the word in the currently opened file

Oddly enough, it seems to only replace in the currently opened file (though other files have a "preview"). I can repro this in both stable and insiders

**Expected Behavior**
VS Code blocks the edit as you're in readonly mode

**Acutal Behavior**
Edit is successful and user is able to replace any number of instances of the found word.

**Comment by joyceerhl** [comment]
This is a known limitation of the multiplexing virtual filesystem provider that RemoteHub register. Whether a RemoteHub filesystem is readonly depends on which virtual repository providers are registered, e.g. `github` files are read-write but `azurerepos` files are readonly. We decided prior to the vscode.dev launch that this wasn't ship-blocking, especially since the plan has always been to add write support for Azure Repos.

If we wanted to address this, we could explore registering the RemoteHub filesystem provider all up as readonly if only Azure Repos repositories are open, though this is slightly complicated by the fact that providers are registered dynamically and whether a filesystem provider is readonly is determined statically at the time of provider registration. +@lszomoru for additional thoughts.

**Comment by lszomoru** [comment]
Rather than complicating the file system provider registration, I would like to aggressively push next milestone to get ADO write support.

**Comment by jepetty** [comment]
That prioritization and logic makes sense to me! Feel free to close this issue until it's something that will make it onto the team's milestone :)

Thanks for the explanation!

**Comment by joyceerhl** [comment]
Closing in favor of https://github.com/microsoft/vscode-remote-repositories-github/issues/117.
