### ISSUE TITLE
Plan for June 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-repositories-github#12]
### UX
- [x] Improve suggestion to index the remote repository @JacksonKearl

### Fundamentals
- [ ] :runner: Ensure a smooth flow between the Remote Repositories and the GHPR extensions @eamodio @alexr00
- [ ] :runner: Easily accessible creation of remote links @eamodio @alexr00
- [ ] :muscle: Explore command line support like `code github.com/org/repo` @eamodio
- [ ] :muscle: Consolidate pickers with the GH core extension and make pickers available for other extensions @eamodio

**Comment by alexr00** [comment]
> Easily accessible creation of remote links

@eamodio I think think that the built in github extension makes the most sense for this, but it still doesn't have a `web` entry point.  The permalink commands in GHPRI now work without sign in, so that's an improvement. Should we just defer this until the github extension is web-ready? Do you know what it will take to get the github extension ready for web?
