### ISSUE TITLE
Diff editor always fails to restore on a reload

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-remote-repositories-github#200]
1. Make a change in GitHub Repositories or Azure Repos
2. Click on the changed file in the SCM view in order to open the diff
3. Reload VS Code
4. :bug: the diff editor fails to restore. Clicking "Try Again" is good enough to restore the editor, seems like the diff editor tries to restore too eagerly before the filesystem provider is registered/available 

![image](https://user-images.githubusercontent.com/30305945/172947451-6556230a-d13b-4dca-b4ba-a691d8b45144.png)

**Comment by joyceerhl** [comment]
I also see the PR diff editor fail to restore on desktop  
![image](https://user-images.githubusercontent.com/30305945/172948496-e53285b3-0317-4f2c-8652-d510dfd70924.png)

**Comment by joyceerhl** [comment]
Doesn't repro in extension development host, 🙃

**Comment by alexr00** [comment]
> Doesn't repro in extension development host, 🙃

I thought I just fixed this... guess this explains why.

**Comment by alexr00** [comment]
With a local repository, I see a pull request diff get restored as expected.

With a remote repository, I get an empty editor:
![image](https://user-images.githubusercontent.com/38270282/173033255-b9c227ff-7aaa-4d18-b229-b8e664fb430a.png)

Either something is happening in a slightly different order or something is taking a different amount of time in a Remote Repository than when local. The fix for the PR diff is to make sure we wait for GHPRI to discover and track all the GitHub repositories associated with the folder instead of implicitly waiting for that by waiting for something else.

**Comment by joyceerhl** [comment]
Sorry, to clarify, I was seeing PR diff editors fail to restore in desktop without Remote Repos involved. That said I realized the original problem here is quite straightforward and is caused by the move to lazy provider registration--the github filesystem provider is not registered at the time that the diff editors attempt to restore, because the github filesystem provider only gets registered on a custom registration hook from Remote Repos. To fix this we can:
- switch any place that is using provider uris to instead use vscode-vfs uris
- ensure the github filesystem provider registers in the GitHub Repositories extension activation method (and same problem exists for the azurerepos filesystem provider)
    - this is probably the better option, but requires exposing Remote Repos extension API and allowing Remote Repos to acquire it, or creating a proxy for the api and making all the calls to it async

**Comment by joyceerhl** [comment]
This should have been addressed in June, closing so it gets verified.
