### ISSUE TITLE
Reopen on the Desktop does not preserve branch context

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode-remote-repositories-github#236]
I tried to test https://github.com/microsoft/vscode-remote-repositories-github/issues/232. In the gif below, in insiders.vscode.dev I go to the branch aiday/issue159064, then I click in the command palette the 'Continue working on' command. Previously I have clicked on the option 'Clone the repository locally and open on desktop' to make a new local copy of VS Code. Insiders is opened but as can be seen in the lower left corner I am on the main branch. Perhaps I am using the feature wrong?

![issueJoyce](https://user-images.githubusercontent.com/61460952/186660896-4911ad88-8ff4-4b8e-9380-6cfb494d5470.gif)

**Comment by joyceerhl** [comment]
@aiday-mar do you happen to have the pre-release of [GitHub Repositories](https://marketplace.visualstudio.com/items?itemName=github.remotehub) installed locally? The intent of Reopen on the Desktop is that it reopens your insiders.vscode.dev/github folder on desktop VS Code but still in a virtual repository (i.e. not a clone onto your local filesystem).

In the GIF above it looks like what opens is an existing local clone of microsoft/vscode, likely because that was the folder that you had open in your most recently closed VS Code window. You should instead have had a new desktop VS Code window open containing the repo and branch you were just looking at.

Would you mind sharing the Remote Repositories output channel on desktop? That should contain some error about `handleUri` or similar.

**Comment by aiday-mar** [comment]
@joyceerhl Hi thanks for your comment, I enabled the GitHub repositories as you suggested and did the steps again. It opened the right branch. I'll add the label verified to this bug.
