### ISSUE TITLE
Please allow local saves of modified files.

### ISSUE THREAD

**Issue by crius-al** [microsoft/vscode-remote-repositories-github#311]
I'm a developer who can not test my LPC code on my local machine because it runs on a mud.
I can not locally clone the files because git runs into problems with invalid file names.
This remote repositories extension is the first time I'm able to edit files in github directly without needing to manually update every file I planned to work on (We have a few developers all working on files simultaneously).
The problem is remote repositories doesn't seem to save the changed files locally, and I need a local copy to sftp to the mud so I can test the code.

I kindly request the ability to save (or at least find) the changed files locally so I can upload my changes to the mud for testing.

**Comment by joyceerhl** [comment]
You can right click on one or more files from the explorer view and select `Download`. Does that help?

**Comment by crius-al** [comment]
> You can right click on one or more files from the explorer view and select `Download`. Does that help?

This helps, thank you.
When I alter the file however, the file I downloaded does not have the changes - even if I save them.
Basically, I have to select to download, and pick the location of the file every time I make changes I want to test.
Which is better?
ctrl-a, ctrl-c, swap window, ctrl-v, ctrl-s.
or
locate the file in the explorer window, right click the file, download the file (there is no shortcut), select the location to save to, save the file.
I'm not sure.

What I want is when I hit ctrl-s in visual studio, the file is saved on my hard drive, and I can immediately upload it to the mud.

**Comment by joyceerhl** [comment]
I think maybe you can implement this functionality in an extension, but only if you are already in VS Code desktop, because Remote Repositories running in the browser cannot access your local filesystem due to browser sandboxing. 

To give more details, I think you could have an extension which subscribes to `vscode.workspace.onDidSaveTextDocument` events for `vscode-vfs` URIs, converts them to `file` URIs for your local filesystem, and writes them to some known location using the `vscode.workspace.fs.writeFile` API. 

Since this is implementable by an extension and is not widely requested, this is unlikely to be something that we implement in the extension itself so I am closing it as not planned.
