### ISSUE TITLE
Searching remote GitHub repos questions

### ISSUE THREAD

**Issue by Liturgist** [microsoft/vscode-remote-repositories-github#322]
Does the extension rely on GitHub created indexes? If so, does that mean that files > 350 KiB are omitted?

Is it possible to script the search of a remote repo?

**Comment by joyceerhl** [comment]
@liturgist The extension does not rely on GitHub created indexes. As mentioned earlier we download and search an archive of the repository instead. https://github.com/microsoft/vscode-remote-repositories-github/issues/320#issuecomment-1496645050 

It's not currently possible to script the search of a remote repository because the files live in memory. It would be great if you could provide context on the use case you have in mind. You could probably write a VS Code extension for that.
