### ISSUE TITLE
"Lost" changes on window reload

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-repositories-github#34]
1) had a repo open with uncommitted changes
2) opened the extension view to disable an extension for this workspace
3) perform required reload of the window
-> changes are gone
4) Open Remote Explorer, see changes are in "some other place"
![image](https://user-images.githubusercontent.com/4674940/124297535-05e84580-db10-11eb-9162-48329c2e8210.png)

**Comment by eamodio** [comment]
This seems to have been caused by https://github.com/microsoft/vscode/commit/b1b44a3910c7df865eea155c3c367c2ec085b2bd where the `storageUri` could change in certain circumstances (including an unresponsive extension host -- which we think is what happened here).

I'm now stripping this new possible suffix from my workspace id, so this will be avoided. I've also opened: https://github.com/microsoft/vscode/issues/128225 so that we could avoid any issues in the future.
