### ISSUE TITLE
github.dev pull does not merge remote modifications into local modifications

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-remote-repositories-github#69]
**This might cause unnoticed data loss on github.dev.**

Steps to reproduce:
* Open a repo with github.dev
* Open that repo in VS Code Desktop
    * Modify *file.txt*: Prepend it with `foo`.
    * Push that change from VS Code Desktop
* Modify *file.txt* in the previously opened github.dev tab: Append it with `bar` (to avoid merge conflicts)
* Try pushing the change

Notice that github.dev notifies the user that they cannot push as the remote contains unfetched changes:

![image](https://user-images.githubusercontent.com/2931520/137929712-472bd36b-00c5-49ab-86f7-f701ae89f68e.png)

* Click on `pull`
* Try pushing the change again
* Observe that pushed something successfully.

**Observe that the pushed commit reverts the commit pushed from VS Code Desktop!**

Effectively, pulling the unfetched commit did not merge the changes into local modified files, even if the merge was conflict-free.
There is no warning of a conflict, which makes the user believe that the `pull` was conflict-free and changes were successfully merged.

## Expected Behavior

Pulling remote commits should also merge them into modified files.
Alternatively, an error message should be shown.

## Context

I'm just noticing that github.dev indeed shows a warning when it automatically notices that someone else already pushed to the remote:

![image](https://user-images.githubusercontent.com/2931520/137934891-a30c4e3d-9e26-4a26-a7cd-73b7e030a4a2.png)

However, after pulling only a `M` is shown:

![image](https://user-images.githubusercontent.com/2931520/137935090-73055754-b9dd-49bb-9308-0b40078b90e3.png)

**Comment by digitarald** [comment]
I just had prior changes made in a planning doc reverted by my commit. I think I picked Sync, as this is also the button label for what I otherwise do when doing git in VS Code on desktop.

**Comment by joyceerhl** [comment]
Started looking into this today. Progress so far:
- There appears to have been a bug for some time where merge conflicts were not being properly detected. This will be fixed following tonight's nightly RemoteHub build.
- The merge-conflict extension which contributes the merge conflict widget is currently not enabled in virtual workspaces. I've put up a PR to enable it: https://github.com/microsoft/vscode/pull/142448.
- The actual changes to support merge conflicts in RemoteHub are very minimal, since we currently do extra work to strip out the conflict markers from the result of the merge function in order to support the simplified merge conflict flow. These changes cannot land until the merge-conflict extension is enabled in virtual workspaces.

With all those changes, here's the result of pulling in conflicting changes in a GitHub repository using RemoteHub:

![image](https://user-images.githubusercontent.com/30305945/152887547-e0dfe671-e354-4803-91e6-1ecc5804c68b.png)

**Comment by joyceerhl** [comment]
I just published a RemoteHub pre-release enabling the new merge conflict flow by default in insiders.vscode.dev. I will continue to polish it over the next few days, in the meantime please give it a try and let me know what you think. 

Out of an abundance of caution, the previous simplified flow will continue to be available via `remoteHub.experimental.useSimplifiedMerge` since this is a behavior change for users. If it is not widely used after a few iterations, I plan to remove this setting.

FWIW, there are still several UI/UX differences between RemoteHub and desktop git. I have fixed some of these, but am documenting some more so I fix them / in case anyone has strong feelings about making RemoteHub more consistent:
![2022-01-05-1714](https://user-images.githubusercontent.com/30305945/153125872-cd2530b4-8e03-40b1-8bd3-ca935110239e.png)

**Comment by hediet** [comment]
Great job! Works as expected now!
