### ISSUE TITLE
Support git-lfs

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-repositories-github#7]
Provide support for repositories that use git-lfs.

**Comment by joyceerhl** [comment]
The latest prerelease of GitHub Repositories on VS Code desktop supports reading LFS files from GitHub with the following setting (same goes for Azure Repos):

```json
{
  "githubRepositories.experimental.lfs.read.enabled": true,
  "azureRepos.experimental.lfs.read.enabled": true
}
```

Caveats:
- [x] No support on web yet due to CORS issues which need to be investigated
- [ ] No support for committing--needs further investigation
- [ ] No support for custom LFS server configuration in gitconfig
- [x] Need to investigate support for Azure Repos
- [ ] Each file is retrieved with a separate request, we could improve performance and reduce network pressure by requesting multiple objects in a single request

**Comment by joyceerhl** [comment]
Latest status: we now support committing LFS files from remote repositories in VS Code desktop with Azure Repos and GitHub. We are still waiting on a CORS update from GitHub to unblock the vscode.dev/github.dev commit scenario, so assigning to April.

**Comment by joyceerhl** [comment]
LFS commit support is now available for GitHub repos in the current insiders.vscode.dev and github.dev. Tracking support for Azure Repos in vscode.dev here: https://github.com/microsoft/vscode-remote-repositories-github/issues/317
